### ISSUE TITLE
Error when requesting password reset token

### ISSUE THREAD

**Issue by frandi** [Polyrific-Inc/OpenCatapult#170]
I've got `Error: Unauthorized` when running `account password resettoken`. Please investigate this.

**Comment by BrainBalaka** [comment]
@frandi It appears this happened because the CLI need to get the user Id by email (API endpoint: `/account/email/{email}`), which require authorization.

What if we change the reset password endpoint url?
> `/account/{userId}/resetpassword` into `/account/email/{email}/resetpassword`

This way, we won't meet authorization problem since we don't need to call the `/account/email/{email}` anymore.

**Comment by frandi** [comment]
Sure, please do. Thanks.

**Comment by BrainBalaka** [comment]
resolved
