### ISSUE TITLE
Add ability to create Database

### ISSUE THREAD

**Issue by BrainBalaka** [Polyrific-Inc/OpenCatapult#288]
Since we're automating the resource creation of GitHub repository and Azure Web App, we should also add  the ability to automatically create the Database instance in DeployDb task

We need to research whether we'd need to add `Azure` as the required service of `EntityFrameworkCore`

**Comment by frandi** [comment]
@BrainBalaka good thinking. However I don't think it's appropriate to add the ability to `EntityFrameworkCore` plugin because it will add unnecessary dependency to specific platform. The database could be in any platform, and they will certainly have different method in instantiating it. We don't want to pollute the plugin's code base with various platform implementations, do we?

If we really think it is important for the task provider to have the ability to create database in Azure SQL, we can always create new plugin that is specific to the platform only, e.g. `EFCoreAzureSQL`.

**Comment by BrainBalaka** [comment]
Agreed. As discussed, the EntityFrameworkCore should be able to create the database if it's deployed in SQL Server, instead of Azure SQL Service. I'm closing this issue for now
